"""Provider-neutral travel-matrix contracts for Smart Planner."""

from .cache import TravelMatrixCache
from .constraints import (DEFAULT_CATEGORY_DURATION_MINUTES,
                          MAX_VISIT_DURATION_MINUTES, DayTimeBudget,
                          VisitDurationResolution, VisitDurationSource,
                          resolve_visit_duration)
from .day_optimizer import (
    DayOptimizationApplyRequest,
    DayOptimizationApplyResult,
    DayCostComparison,
    DayItemSnapshot,
    DayManualReorderRequest,
    DayOptimizationDiagnostic,
    DayOptimizationDiagnosticKind,
    DayOptimizationPreviewRequest,
    DayOptimizationResult,
    DayRouteCost,
    DayScheduleEstimate,
    DayScheduleItemEstimate,
    TripOptimizer,
)
from .osrm_table import OSRMTableRoutingProvider
from .trip_allocator import (
    TripAllocationDay,
    TripAllocationDiagnostic,
    TripAllocationDiagnosticKind,
    TripAllocationObjective,
    TripAllocationResult,
    TripAllocator,
    TripOptimizationApplyRequest,
    TripOptimizationApplyResult,
    TripOptimizationPreviewResult,
    TripPlanningSnapshotAssignment,
    TripPlanningTotals,
    TripPlanningSettings,
)
from .routing import (
    CoordinateSnapshot,
    RoutingCapability,
    RoutingFailure,
    RoutingFailureKind,
    RoutingProfile,
    RoutingProvider,
    TravelLocation,
    TravelMatrix,
    TravelMatrixRequest,
    TravelMatrixResult,
    get_routing_capability,
    unsupported_matrix_failure,
)

__all__ = [
    "CoordinateSnapshot",
    "DEFAULT_CATEGORY_DURATION_MINUTES",
    "DayOptimizationApplyRequest",
    "DayOptimizationApplyResult",
    "DayCostComparison",
    "DayItemSnapshot",
    "DayManualReorderRequest",
    "DayOptimizationDiagnostic",
    "DayOptimizationDiagnosticKind",
    "DayOptimizationPreviewRequest",
    "DayOptimizationResult",
    "DayRouteCost",
    "DayScheduleEstimate",
    "DayScheduleItemEstimate",
    "DayTimeBudget",
    "MAX_VISIT_DURATION_MINUTES",
    "OSRMTableRoutingProvider",
    "RoutingCapability",
    "RoutingFailure",
    "RoutingFailureKind",
    "RoutingProfile",
    "RoutingProvider",
    "TravelLocation",
    "TravelMatrixCache",
    "TravelMatrix",
    "TravelMatrixRequest",
    "TravelMatrixResult",
    "TripAllocationDay",
    "TripAllocationDiagnostic",
    "TripAllocationDiagnosticKind",
    "TripAllocationObjective",
    "TripAllocationResult",
    "TripAllocator",
    "TripOptimizationApplyRequest",
    "TripOptimizationApplyResult",
    "TripOptimizationPreviewResult",
    "TripPlanningSnapshotAssignment",
    "TripPlanningTotals",
    "TripPlanningSettings",
    "TripOptimizer",
    "VisitDurationResolution",
    "VisitDurationSource",
    "get_routing_capability",
    "resolve_visit_duration",
    "unsupported_matrix_failure",
]
